class Shape:
    def name(self) -> str: ...

    def perimeter(self) -> float: ...

    def area(self) -> float: ...

    def __str__(self) -> str: ...


class ShapeFactory:

    @staticmethod
    def create(name: str) -> Shape: ...

    @staticmethod
    def create_with(name: str, dims: list[float]) -> Shape : ...

    @staticmethod
    def is_known(name: str) -> bool: ...

    @staticmethod
    def number_known() -> int: ...

