# -------------------------------------------------------------------------------
# "Basic" Shapes
# -------------------------------------------------------------------------------
class Circle:
    @property
    def name(self) -> str: ...
    def perimeter(self) -> float: ...
    def area(self) -> float: ...
    def __str__(self) -> str: ...

class Square:
    @property
    def name(self) -> str: ...
    def perimeter(self) -> float: ...
    def area(self) -> float: ...
    def __str__(self) -> str: ...

class Triangle:
    @property
    def name(self) -> str: ...
    def perimeter(self) -> float: ...
    def area(self) -> float: ...
    def __str__(self) -> str: ...

class EquilateralTriangle:
    @property
    def name(self) -> str: ...
    def perimeter(self) -> float: ...
    def area(self) -> float: ...
    def __str__(self) -> str: ...

class RightTriangle:
    @property
    def name(self) -> str: ...
    def perimeter(self) -> float: ...
    def area(self) -> float: ...
    def __str__(self) -> str: ...

# -------------------------------------------------------------------------------

class Shape:
    @property
    def name(self) -> str: ...
    def perimeter(self) -> float: ...
    def area(self) -> float: ...
    def __str__(self) -> str: ...

class ShapeFactory:
    @staticmethod
    def create(name: str) -> Shape: ...

    @staticmethod
    def create_with(name: str, dims: list[float]) -> Shape: ...

    @staticmethod
    def is_known(name: str) -> bool: ...

    @staticmethod
    def number_known() -> int: ...

    @staticmethod
    def list_known() -> str: ...
