[config]
default_to_workspace = false

[env]
PYTHON = "python3.11"
PYO3_PYTHON="python3.11"

[tasks.build-ffi-flow]
condition = { files_modified = { input = ["**/Cargo.toml", "**/src/**/*.rs"], output = ["./target/**/*shape*"] }, platforms = ["linux"]}
dependencies = [ "build", "copy-lib" ]

[tasks.build]
condition = { files_modified = { input = ["**/Cargo.toml", "**/src/**/*.rs"], output = ["./target/**/*prime*"] } }
private = true
command = "cargo"
args = ["build", "--release"]

[tasks.clean]
command = "cargo"
args = [ "clean" ]

[tasks.run-rust]
dependencies = ["build"]
command = "./target/release/shapes_bin"
args = ["${@}"]

[tasks.test-rust]
dependencies = ["build"]
command = "cargo"
args = ["test"]

[tasks.bench-rust]
dependencies = ["build"]
command = "cargo"
args = ["bench"]
