from collections.abc import Sequence
from os import PathLike
from typing import Any, Final, final

from _typeshed import Incomplete

@final
class Circle:
    PI: Final[float]
    TAU: Final[float]
    def __deepcopy__(self, /, _memo: Any) -> Circle: ...
    def __new__(cls, /, radius: float = 1.0) -> Circle: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def area(self, /) -> float: ...
    @property
    def diameter(self, /) -> float: ...
    @property
    def name(self, /) -> str: ...
    def perimeter(self, /) -> float: ...
    @property
    def radius(self, /) -> float: ...
    @radius.setter
    def radius(self, /, val: float) -> None: ...

@final
class EquilateralTriangle:
    def __deepcopy__(self, /, _memo: Any) -> EquilateralTriangle: ...
    def __new__(cls, /, side: float = 1.0) -> EquilateralTriangle: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def area(self, /) -> float: ...
    @property
    def name(self, /) -> str: ...
    def perimeter(self, /) -> float: ...
    @property
    def side(self, /) -> float: ...
    @side.setter
    def side(self, /, val: float) -> None: ...

@final
class RightTriangle:
    def __deepcopy__(self, /, _memo: Any) -> RightTriangle: ...
    def __new__(cls, /, base: float = 1.0, height: float = 1.0) -> RightTriangle: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def area(self, /) -> float: ...
    @property
    def base(self, /) -> float: ...
    @base.setter
    def base(self, /, val: float) -> None: ...
    @property
    def height(self, /) -> float: ...
    @height.setter
    def height(self, /, val: float) -> None: ...
    @property
    def hypotenuse(self, /) -> float: ...
    @property
    def name(self, /) -> str: ...
    def perimeter(self, /) -> float: ...

@final
class Shape:
    def __str__(self, /) -> str: ...
    def area(self, /) -> float: ...
    @property
    def name(self, /) -> str: ...
    def perimeter(self, /) -> float: ...
    def trigger_conversion_error(self, /) -> None: ...
    def try_as_circle(self, /) -> Circle: ...
    def try_as_equilateral_triangle(self, /) -> EquilateralTriangle: ...
    def try_as_right_triangle(self, /) -> RightTriangle: ...
    def try_as_square(self, /) -> Square: ...
    def try_as_triangle(self, /) -> Triangle: ...

@final
class ShapeFactory:
    @staticmethod
    def create(name: str) -> Shape:
        """
        Create a Shape

        # Arguments

          * `name` shape to be created
        """

    @staticmethod
    def create_with(name: str, dims: Sequence[float]) -> Shape:
        """
        Create a Shape with specified dimensions.

        # Arguments

          * `name` shape to be created
          * `dims` input dimensions
        """

    @staticmethod
    def is_known(name: str) -> bool:
        """
        Determine whether a given shape is known

        # Arguments

         * `name` the shape for which to query
        """

    @staticmethod
    def list_known() -> str:
        """
        List the known shapes, one per line
        """

    @staticmethod
    def number_known() -> int: ...

@final
class ShapeParser:
    @staticmethod
    def read_shape(line: str) -> Shape: ...
    @staticmethod
    def read_shapes(file_path: str | PathLike[str]) -> list[Shape]: ...

@final
class Square:
    def __deepcopy__(self, /, _memo: Any) -> Square: ...
    def __new__(cls, /, side: float = 1.0) -> Square: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def area(self, /) -> float: ...
    @property
    def name(self, /) -> str: ...
    def perimeter(self, /) -> float: ...
    @property
    def side(self, /) -> float: ...
    @side.setter
    def side(self, /, val: float) -> None: ...

@final
class Triangle:
    def __deepcopy__(self, /, _memo: Any) -> Triangle: ...
    def __new__(cls, /, a: float = 1.0, b: float = 1.0, c: float = 1.0) -> Triangle: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def area(self, /) -> float: ...
    @property
    def name(self, /) -> str: ...
    def perimeter(self, /) -> float: ...
    @property
    def side_a(self, /) -> float: ...
    @side_a.setter
    def side_a(self, /, val: float) -> None: ...
    @property
    def side_b(self, /) -> float: ...
    @side_b.setter
    def side_b(self, /, val: float) -> None: ...
    @property
    def side_c(self, /) -> float: ...
    @side_c.setter
    def side_c(self, /, val: float) -> None: ...

def __getattr__(name: str) -> Incomplete: ...
