class ShapeConversionError(Exception):
    def __new__(cls, /, requested: str, actual: str) -> ShapeConversionError: ...
    def __str__(self, /) -> str: ...
    @property
    def actual(self, /) -> str: ...
    @property
    def requested(self, /) -> str: ...
